version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: node:10.16.3
    steps:
      - checkout
      - restore_cache:
          key: yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - restore_cache:
            keys:
              - always-
      - run: yarn build
      - save_cache:
          key: always-{{ epoch }}
          paths:
            - public
      - run:
          name: Send build stats to Relative CI
          command: node_modules/.bin/relative-ci-agent
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    working_directory: ~/repo
    docker:
      - image: node:10.16.3
    steps:
      - attach_workspace:
          at: .
      - run: yarn test
  docs:
    working_directory: ~/repo
    docker:
      - image: node:10.16.3
    steps:
      - attach_workspace:
          at: .
      - run: npm run build-storybook
      - store_artifacts:
          path: storybook-static
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - docs:
          requires:
            - build
