export const lexicalTheme = {
  hashtag: "text-blue-600 hover:underline cursor-pointer",
  link: "text-blue-600 hover:underline cursor-pointer",
  text: {
    bold: "font-bold",
    italic: "italic",
    underline: "underline",
    strikethrough: "line-through",
    code: "bg-gray-100 text-red-600 px-1 rounded font-mono text-sm",
  },
  code: "block bg-gray-900 text-gray-100 p-4 rounded-lg font-mono text-sm overflow-x-auto",
  codeHighlight: {
    atrule: "text-purple-400",
    attr: "text-green-400",
    boolean: "text-orange-400",
    builtin: "text-cyan-400",
    cdata: "text-gray-500",
    char: "text-green-400",
    class: "text-yellow-400",
    "class-name": "text-yellow-400",
    comment: "text-gray-500 italic",
    constant: "text-orange-400",
    deleted: "text-red-400",
    doctype: "text-gray-500",
    entity: "text-red-400",
    function: "text-blue-400",
    important: "text-red-400",
    inserted: "text-green-400",
    keyword: "text-purple-400",
    namespace: "text-red-400",
    number: "text-orange-400",
    operator: "text-cyan-400",
    prolog: "text-gray-500",
    property: "text-orange-400",
    punctuation: "text-gray-400",
    regex: "text-red-400",
    selector: "text-green-400",
    string: "text-green-400",
    symbol: "text-orange-400",
    tag: "text-pink-400",
    url: "text-cyan-400",
    variable: "text-red-400",
  },
  list: {
    nested: {
      listitem: "ml-6",
    },
    ol: "list-decimal list-inside",
    ul: "list-disc list-inside",
    listitem: "ml-2",
  },
  heading: {
    h1: "text-3xl font-bold mt-6 mb-4",
    h2: "text-2xl font-bold mt-5 mb-3",
    h3: "text-xl font-bold mt-4 mb-2",
    h4: "text-lg font-bold mt-3 mb-2",
    h5: "text-base font-bold mt-2 mb-1",
    h6: "text-sm font-bold mt-2 mb-1",
  },
  quote: "border-l-4 border-gray-300 pl-4 italic my-4 text-gray-700",
};